manage_groups:
  - name: histudy
  - name: kakogawa_infra
  - name: webadmin

manage_acounts:
  - name: wate
    admin: true
    password: "{{ lookup('csvfile', 'wate file=secret/password.csv delimiter=,') }}"
    groups:
      - histudy
      - kakogawa_infra
      - webadmin
    authorized_keys:
      - key: https://github.com/wate.keys
  - name: sperkbird
    admin: true
    password: "{{ lookup('csvfile', 'sperkbird file=secret/password.csv delimiter=,') }}"
    groups:
      - histudy
      - kakogawa_infra
    authorized_keys:
      - key: https://github.com/sperkbird.keys
  - name: 223n
    password: "{{ lookup('csvfile', '223n file=secret/password.csv delimiter=,') }}"
    groups:
      - histudy
      - kakogawa_infra
      - webadmin
    authorized_keys:
      - key: https://github.com/223n.keys
  - name: fu7mu4
    password: "{{ lookup('csvfile', 'fu7mu4 file=secret/password.csv delimiter=,') }}"
    groups:
      - histudy
    authorized_keys:
      - key: https://github.com/fu7mu4.keys
  - name: nogajun
    password: "{{ lookup('csvfile', 'nogajun file=secret/password.csv delimiter=,') }}"
    groups:
      - histudy
      - webadmin
    authorized_keys:
      - key: https://github.com/nogajun.keys
