dehydrated_cfg:
  challengetype: dns-01
  contact_email: admin@mail.histudy.jp

dehydrated_domains:
  - name: histudy.jp
    domains:
      - histudy.jp
      - "*.histudy.jp"

dehydrated_hook_deploy_challenge: |
  lexicon sakuracloud create ${DOMAIN} TXT --name="_acme-challenge.${DOMAIN}.${DOMAIN}" --content="${TOKEN_VALUE}" --auth-token="{{ lookup('env', 'LEXICON_SAKURACLOUD_TOKEN') }}" --auth-secret="{{ lookup('env', 'LEXICON_SAKURACLOUD_SECRET') }}"
  sleep 30

dehydrated_hook_clean_challenge: |
  lexicon sakuracloud delete ${DOMAIN} TXT --name="_acme-challenge.${DOMAIN}.${DOMAIN}" --content="${TOKEN_VALUE}" --auth-token="{{ lookup('env', 'LEXICON_SAKURACLOUD_TOKEN') }}" --auth-secret="{{ lookup('env', 'LEXICON_SAKURACLOUD_SECRET') }}"

dehydrated_hook_deploy_cert: |
  if [ -e /lib/systemd/system/nginx.service ]; then
    /bin/systemctl reload nginx
  fi


nginx_vhosts:
  # デフォルトのサイト
  - name: default
    default: true
    server_name: histudy.jp
    access_log: /var/log/nginx/access.log
    error_log: /var/log/nginx/error.log
    document_root: /var/www/html
    index:
      - index.html
      - index.htm
    locations:
      - pattern: /
        content: |
          try_files $uri $uri/ /index.php?$query_string;
      - pattern: "/\\.ht"
        match_type: "~"
        content: "deny all;"
    # ssl:
    #   certificate: /var/lib/dehydrated/certs/histudy.jp/fullchain.pem
    #   certificate_key:  /var/lib/dehydrated/certs/histudy.jp/privkey.pem
    #   hsts: "max-age=15768000;"
    #   stapling: true
    #   stapling_verify: true
  # MackerelのNginxのステータス取得用
  - name: status
    server_name: localhost
    listen: 8080
    access_log: 'off'
    locations:
      - pattern: /nginx_status
        content: |
          stub_status on;
          allow 127.0.0.1;
          deny all;
